### ISSUE TITLE
Verilator: Linker failures not captures

### ISSUE THREAD

**Issue by wallento** [olofk/fusesoc#116]
Verilator pipes the linker output through `c++filt`, so that the return code is not the linker error, but the `c++filt` return code. Maybe we can handle it here, but I suppose the proper way is in verilator itself.

**Comment by olofk** [comment]
Did you file a bug report for verilator regarding this? As you say, I think that's where we need to handle this

**Comment by olofk** [comment]
This is being worked on in Verilator https://www.veripool.org/issues/1265-Verilator-Fix-status-code-of-generated-Makefile . Nothing to do for FuseSoC
