### ISSUE TITLE
List of valid file types

### ISSUE THREAD

**Issue by wallento** [olofk/fusesoc#121]
At least a list of all file types should be kept and checked against.

**Comment by olofk** [comment]
We could do something like this. https://gist.github.com/olofk/dfc082e69a9056c7f8aca9a754cbfa1e

The drawback would of course be that it needs to be updated whenever a backend supports a new format, but maybe that's not too big of an issue

**Comment by wallento** [comment]
Yeah, I think this would be proper. It will also put more control over the backend cleanness (at least a bit).

**Comment by olofk** [comment]
This has been fixed in 93d004dbd72cbc486e34ed44adc78ccdf4dc1f75
