### ISSUE TITLE
NameError: name 'parser' is not defined

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#189]
A up-to-date fusesoc checkout (master) gives the following error when called without any command line arguments:

~~~
philipp@powerashley:~/src/fusesoc> ~/.local/bin/fusesoc
Traceback (most recent call last):
  File "/home/philipp/.local/bin/fusesoc", line 11, in <module>
    load_entry_point('fusesoc', 'console_scripts', 'fusesoc')()
  File "/home/philipp/src/fusesoc/fusesoc/main.py", line 488, in main
    parser.print_help()
NameError: name 'parser' is not defined
~~~

**Comment by olofk** [comment]
Thanks! Fixed (reopeon if I'm wrong)

**Comment by imphil** [comment]
Fixed, thanks.

**Comment by tianbartek** [comment]
I have the same problem. How to fix? Can you be more specific

**Comment by imphil** [comment]
@olofk fixed this in https://github.com/olofk/fusesoc/commit/8c06ad7d369672ca3d9fc68c09e417faf97d44b2. If you experience the same or a similar problem, please make sure that you're running the latest fusesoc version. If that's the case, please open a new issue, since yours is likely different from mine (which was fixed).

**Comment by MPrakash007** [comment]
data = Parser.parse_args()
NameError: name 'Parser' is not defined

**Comment by carminestore** [comment]
Can someone please help me..i Have the same error

**Comment by imphil** [comment]
@carminestore can you please open a new issue and include the version of fusesoc you're using, more information about your system (Python version, etc.), and the command you're trying to run?

**Comment by alessiobartels98** [comment]
parsed = parser.from_file('analisi.pdf')
#print(parsed['content'])
pdf = parsed["content"]
pdf = pdf.split("\n")
#print(len(pdf))
print(pdf)

name Error: name 'Parser' is not defined

**Comment by alessiobartels98** [comment]
can someone help me please?

**Comment by imphil** [comment]
This does not look like fusesoc code?
