### ISSUE TITLE
Use tox for tests in travis

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#213]
Currently fusesoc runs tests in travis with "pip install .". This prevents catching bugs which happen due to wrong packaging, i.e. when installing from sdist. Using tox first creates packages and then installs and tests them, making the test results more reliable in this regard. This would have prevented e.g. 165fa40bde15aea8f53eeddc20b87fcdc37f258a

**Comment by olofk** [comment]
I'm not sure it would have prevented that since there was no test case for the spyglass backend, so the templates were never requested
