### ISSUE TITLE
Vivado Backend: Add jobs Parameter

### ISSUE THREAD

**Issue by ThomasHornschuh** [olofk/fusesoc#225]
It was a part of closed issue #203, suggestion was to create an extra issue for this just to not forget.

It would be very helpful to have the possibility to add the -jobs parameter to the run tcl, e.g.:
launch_runs impl_1 -jobs 6

Settings jobs can greatly improve build time of Vivado when running on multi core CPUs.

**Comment by imphil** [comment]
It should be possible to do something like that with a TCL file passed to Vivado as source file where you set the number of jobs. If that's not doing the trick we'd need to enhance Vivado support in edalize; please open an issue there if that's still relevant.
