### ISSUE TITLE
ghdl analyze_options are not passed to the elab-run command

### ISSUE THREAD

**Issue by ThomasHornschuh** [olofk/fusesoc#227]
Analyze_options like e.g. --ieee=synopsys  must also be passed to the --elab-run command because when using the mcode backend the analyze phase does not generate any object files, so all compilation is done during elab-run. The usage of elab-run is
`--elab-run <[elab_options...] primary_unit [secondary_unit] [run_options...]>`
The analyze_options must be passed at the elab_options position.

I changed the respective line in ghdl.py  to
`ghdl --elab-run $(ANALYZE_OPTIONS)  $(TOPLEVEL) $(RUN_OPTIONS) $(EXTRA_OPTIONS)`

Unfortunately I have not updated fusesoc since a while, so I may use an outdated version and because I have no time in the next 2-3 weeks to make such an update I'm not able to create a pull request. So I hope it is ok to just post this as an issue.

**Comment by olofk** [comment]
Closed with https://github.com/olofk/edalize/issues/11
