### ISSUE TITLE
Core file parser causes a 'list index out of range' error when encountering an empty first line

### ISSUE THREAD

**Issue by getziadz** [olofk/fusesoc#246]
The Core file parser causes a 'list index out of range' error when encountering an empty first line.
.split()[0] assumes a non-empty first line.

```python
class Core(object):

    def __new__(cls, *args, **kwargs):
        with open(args[0]) as f:
            first_line = f.readline().split()[0]
```
--------------------------------------------------------------------------^

File ".../fusesoc/fusesoc/core.py", line 14, in __new__
    first_line = f.readline().split()[0]
IndexError: list index out of range

**Comment by olofk** [comment]
Thanks for reporting! This should hopefully be fixed now with b45a220287510134ef713ca21efdd2c3e8896bf1 that should make FuseSoC just see it's an invalid file, warn about it and ignore the file. Please reopen if this doesn't solve your issue
