### ISSUE TITLE
Vivado gui quits immediately after xsim simulation completes (when launched from fusesoc)

### ISSUE THREAD

**Issue by djcopley** [olofk/fusesoc#283]
In my core file:
```
...
targets:
  ...
  sim:
      xsim:
        xelab_options: [--timescale, 1ns/1ns]
        xsim_options: [--gui, --wdb, sim.wdb, --view, FirFilter_tb_behave.wcfg]
   ...
```
When I run simulation: Vivado gui boots up -> simulation begins -> finishes abruptly -> gui closes before I can inspect the waveforms. Is fusesoc terminating the child process after the sim completes?

**Comment by olofk** [comment]
Hmm.. I have never tried to add the --gui flag that way. Eventually I hope to offer a standardized way to launch tools in GUI mode, but for now there exists partial support in some tools (including xsim). The way to do this is to remove the `--gui` flag from your xsim_options and:

1. Run fusesoc with the `--setup` flag, e.g. `fusesoc run --setup --target=yourtarget yourcore --your_other_options`
2. Go to the work root (e.g. `cd build/your_core/your_target-xsim` and run `make run-gui`

Looking at how this is implemented, I'm pretty sure there are more clever ways to do this but this is what we have right now
