### ISSUE TITLE
Problem after adding library without sync-type.

### ISSUE THREAD

**Issue by m-kru** [olofk/fusesoc#294]
User can add library with `fusesoc library add my_lib url` without specifying `sync-type`, but if he later executes `fusesoc update` there is an error `ERROR: Invalid sync-type 'None' for library 'my_lib' - skipping`.

**Comment by olofk** [comment]
Ouch. This is bad. :(

**Comment by olofk** [comment]
Fixed with 95318a006b6f2dbb2d9ee7610d95bdfcfb28524d
