### ISSUE TITLE
error when run fusesoc simulation

### ISSUE THREAD

**Issue by zhanjf** [olofk/fusesoc#312]
hi,
when I execute the command
fusesoc run --target=sim swervolf

the following error met,

INFO: Generating ::swervolf-swerv_default_config:0
Traceback (most recent call last):
File "/home/work/.cache/fusesoc/chipsalliance.org_cores_SweRV_EH1_1.4/configs/swerv_config_gen.py", line 2, in
from fusesoc.capi2.generator import Generator
ImportError: No module named fusesoc.capi2.generator
ERROR: Setup failed : "python /home/work/.cache/fusesoc/chipsalliance.org_cores_SweRV_EH1_1.4/configs/swerv_config_gen.py /home/work/.cache/fusesoc/generated/swervolf-swerv_default_config_0/swerv_default_config_input.yml" exited with an error code. See stderr for details.

Thanks!

**Comment by imphil** [comment]
It looks like either you're using an outdated version of FuseSoC, or something in your system setup is not quite right. Please update fusesoc and try again. Closing as this is quite old and you've likely resolved the problem by now one way or the other.
