### ISSUE TITLE
Enable PR builds for readthedocs

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#331]
ReadTheDocs has an experimental feature to enable pull-request builds. To get added to their beta the repo owner needs to mail them, instructions are here: https://blog.readthedocs.com/building-docs-for-pull-requests/ 

This is actually quite nice to see doc changes rendered in a PR, see https://github.com/cocotb/cocotb/pull/1282 for an example (look at the " continuous-documentation/read-the-docs" check and click on "Details")

@olofk can you enable that feature?

**Comment by olofk** [comment]
Mail sent. Will keep you posted

**Comment by olofk** [comment]
This should be done now. Not sure how to test it. Can you let me know if it works as expected?

**Comment by imphil** [comment]
It should be visible once a new PR is opened, I'll check that on the next one.

**Comment by imphil** [comment]
No, doesn't work yet. I think I had to remove the RTD webhook in the GitHub project and then re-add it through the RTD admin interface when I did the same thing for cocotb.

**Comment by olofk** [comment]
Done now. Thanks for iniating this
