### ISSUE TITLE
fusesoc run and fusesoc sim

### ISSUE THREAD

**Issue by rahulraveendran15-coder** [olofk/fusesoc#343]
Hi,

Can you please tell the how to use the "fusesoc sim <>" and what is its usage? what is the difference between fusesoc run and fusesoc sim?
 right now in all tutorials and manuals "fusesoc run <>" usage is described

**Comment by imphil** [comment]
fusesoc sim is a deprecated command, you only want to use fusesoc run.

**Comment by rahulraveendran15-coder** [comment]
Thank you
