### ISSUE TITLE
How to run core with two different versions

### ISSUE THREAD

**Issue by rahulraveendran15-coder** [olofk/fusesoc#351]
How to run if have two different version and revision of cores

1. name : ::wiredelay:1-r1 
2. name : ::wiredelay:2-r1
3. name : ::wiredelay:1-r2

what will be the core  name i need to provide in these 3 cases
fusesoc run --target=sim <corename> what needs to be in place of core name in version and revision is changing in these 3

**Comment by olofk** [comment]
fusesoc run --target=sim "::wiredelay:1-r1"
    fusesoc run --target=sim "::wiredelay:2-r1"
    fusesoc run --target=sim "::wiredelay:1-r2"

should work. You can also do things like `fusesoc run --target=sim "<=::wiredelay:1-r2"` to get the highest version that is less than or equal to version 1-r2.
