### ISSUE TITLE
Is it possible to add relative paths in fusesoc.conf file

### ISSUE THREAD

**Issue by rahulraveendran15-coder** [olofk/fusesoc#352]
@olofk Is  it possible to add relative paths in fusesoc.conf file?
I need to checkin thefusesoc.conf file to my master repository so that everyone  within the same project can use  the same .conf file without generating or adding by themselves while using fusesoc(They can directly fusesoc with target), no other setup liking adding library and all is not required.

**Comment by olofk** [comment]
Yes. Relative paths are fine

**Comment by rahulraveendran15-coder** [comment]
I have tried adding relative paths  like below
```
#!/usr/bin/env python3
import os
   root = os.path.dirname(os.path.realpath(__file__))
[library.checkcore]
location = root + "./"
sync-uri = ./
sync-type = local
auto-sync = true

```

But its not able to recognise this import os keyword and rest
Could you please help me on this

**Comment by imphil** [comment]
fusesoc.conf is not a Python script, it's a config file. So please remove all python code.

`location = .` should be sufficient.
