### ISSUE TITLE
latest release ?

### ISSUE THREAD

**Issue by csantosb** [olofk/fusesoc#423]
Can we consider 1.11.0 as latest release ? https://github.com/olofk/fusesoc/releases

**Comment by FFY00** [comment]
It is the latest release, but github does not consider it a "release" if you just push a git tag. You need to also create a release in the UI (or via the API), it's a bit ridiculous IMO.

Perhaps the release process could be automated to avoid this.

**Comment by csantosb** [comment]
Fine with me, then.

**Comment by imphil** [comment]
I've added the GH release now.

**Comment by csantosb** [comment]
Great, thanks !
