### ISSUE TITLE
Disable AppVeyor GH integration

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#445]
We currently get a failing CI test for each PR:

![grafik](https://user-images.githubusercontent.com/1467123/99591392-a0af6c00-29e6-11eb-86eb-d3c290a7282d.png)

This is due to AppVeyor not finding a config file any more (which is expected).

@olofk can you deactive the AppVeyor integration in the GH settings of this repository?

**Comment by olofk** [comment]
Should be removed now. Hmm.. does this mean we dont' do any testing on Windows platforms anymore?

**Comment by imphil** [comment]
We test Windows, macOS and Linux with GitHub Actions now, we didn't loose any coverage (on the contrary, we expanded the matrix slightly).
