### ISSUE TITLE
Use pathlib for paths in FuseSoC

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#458]
FuseSoC operates on file paths quite a lot; currently, most of them are passed around as strings. This makes it hard to distinguish them from just a file name. We also don't consistently use helpers like `os.path.join()`, introducing subtle problems with cross-platform compatibility.

With pathlib and Python 3.6+ we get a nicely typed, easy to use way to represent file paths. We could use it as-is, or expand it to include the base directory (working directory) when handling (and preserving) relative paths across FuseSoC.

**Comment by olofk** [comment]
Remind me, what did we say about Python 3.5 support? We want to increase the minimum version to 3.6 before doing this, right?
