### ISSUE TITLE
Delete "rtd" and "master" branch/build on ReadTheDocs

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#464]
On readthedocs we have multiple versions of the docs, including an outdated "rtd" and a duplicated "master" version (https://readthedocs.org/projects/fusesoc/versions/). @olofk can you log into RTD and delete the rtd and master versions? We should only keep the "latest" and "stable" versions, and (later) additionally one version for each release.

**Comment by olofk** [comment]
Think I got it. Please confirm and close

**Comment by imphil** [comment]
Hm, strangely https://fusesoc.readthedocs.io/en/rtd/tutorials/1-getting_started.html is still being served. I read through https://github.com/readthedocs/readthedocs.org/issues/1408 and it seems like previously RTD didn't fully delete the artifacts, but the issue reads to me that might be resolved now.

@olofk just to confirm: Even if you log in https://readthedocs.org/projects/fusesoc/versions/ doesn't show the "rtd" version any more?

(The problem is that the rtd URL is one of the first Google hits if you search for "fusesoc tutorial", and we don't want to point people to an outdated tutorial when they want to get started with FuseSoC.)

**Comment by olofk** [comment]
Ouch. That sounds bad. I can't find any reference to the rtd and master branches in the docs so I have no idea what the problem is. Maybe just reach out to rtd and see if they know

**Comment by imphil** [comment]
Filed https://github.com/readthedocs/readthedocs.org/issues/8174 upstream to ask for help.

**Comment by imphil** [comment]
Looks good now, the branches are gone, and googling for `fusesoc tutorial` doesn't bring up the dead pages any more (at least for me).
