### ISSUE TITLE
Can't "make install" after the lastest commit

### ISSUE THREAD

**Issue by tmd-set** [olofk/fusesoc#52]
As of the Tuesday commit which section was moved, I can't run "make install" without problem. Just "make" is OK, but an error appear with "make install":
````
Byte-compiling python modules...
__init__.pygithub.pyopencores.pyurl.py
Byte-compiling python modules (optimized versions) ...
__init__.pygithub.pyopencores.pyurl.py
make[2]: *** No rule to make target `fusesoc/section/__init__.py', needed by `install-sectionPYTHON'.  Stop.
````
Environment: Ubuntu 14.04, Python 2.7

**Comment by olofk** [comment]
I think this problem is obsolete now. It still affects people who are updating from a version before may 29, 2014, but hopefully people have had time to update by now
