### ISSUE TITLE
Allow Cyclone V FPGAs to be programmed 

### ISSUE THREAD

**Issue by somhi** [olofk/fusesoc#538]
somewhat related to  Issue #170 

This works, but needs to be added somehow into fusesoc to define the FPGA is the second device

```
quartus_pgm --mode=jtag -o "p;fusesoc_utils_blinky_1_1.sof@2"
            # The @2 selects the second device in the JTAG chain, because this chip
            # puts the ARM cores first.
```

**Comment by imphil** [comment]
I haven't tried it myself, but you should be able to use the `board_device_index` tool option: https://fusesoc.readthedocs.io/en/latest/ref/capi2.html#quartus

**Comment by somhi** [comment]
It works, thanks!!
