### ISSUE TITLE
Adding tcl cmd prior to implementation run 

### ISSUE THREAD

**Issue by aignacio** [olofk/fusesoc#539]
Hey everyone,

thanks for the project, since I started using it, I have been evangelising people about it =). I have a simple question which regards of adding the tcl command below prior to the synthesis/implementation step. I have tried to add in the top of the .xdc but had no luck with Vivado, for every run I see the DRC violations during impl. of unconstrained pins which stops the progress of my build. Can you point me if there's an easy  way of adding it into my core file?

```tcl
set_property BITSTREAM.General.UnconstrainedPins {Allow} [current_design]
```

**Comment by sjalloq** [comment]
Have a look at the hooks example in Open Titan: https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/chip_earlgrey_nexysvideo.core

**Comment by aignacio** [comment]
Thanks, solved!
