### ISSUE TITLE
No module named 'edalize.tools.spi_nor_config_generator' 

### ISSUE THREAD

**Issue by soronpo** [olofk/fusesoc#541]
Followed the getting started instructions but get the following error when running `fusesoc`
```
Traceback (most recent call last):
  File "/home/tealc/.local/bin/fusesoc", line 5, in <module>
    from fusesoc.main import main
  File "/home/tealc/.local/lib/python3.8/site-packages/fusesoc/main.py", line 28, in <module>
    from fusesoc.coremanager import CoreManager, DependencyError
  File "/home/tealc/.local/lib/python3.8/site-packages/fusesoc/coremanager.py", line 16, in <module>
    from fusesoc.core import Core
  File "/home/tealc/.local/lib/python3.8/site-packages/fusesoc/core.py", line 9, in <module>
    from fusesoc.capi2.core import Core as Capi2Core
  File "/home/tealc/.local/lib/python3.8/site-packages/fusesoc/capi2/core.py", line 908, in <module>
    for backend in get_edatools():
  File "/home/tealc/Downloads/edalize/edalize/__init__.py", line 38, in get_edatools
    return [get_edatool(pkg) for pkg in walk_tool_packages()]
  File "/home/tealc/Downloads/edalize/edalize/__init__.py", line 38, in <listcomp>
    return [get_edatool(pkg) for pkg in walk_tool_packages()]
  File "/home/tealc/Downloads/edalize/edalize/__init__.py", line 22, in get_edatool
    return getattr(import_module("{}.{}".format(__name__, name)), name.capitalize())
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'edalize.tools.spi_nor_config_generator'
```

**Comment by olofk** [comment]
I'm not sure what's going on here but I have a theory at least. Edalize finds its backends dynamically by looking at which modules that exist in the edalize root directory. I see that it's looking for a `edalize.tools.spi_nor_config_generator` but no such thing exists in Edalize. Do you know what that is and where it is located? Knowing that would provide another puzzle piece

**Comment by soronpo** [comment]
At first I have not installed `edalize` at all, and just followed the `fusesoc` instructions. I also tried installing `edalize` with not much change. I have a VBox machine with Ubuntu 20.04 and docker with 18.04. Both with the same issue.

**Comment by GuzTech** [comment]
I have the exact same issue. I installed fusesoc on my work PC `pip install fusesoc` which installed version 1.12.0. It also installed edalize version 0.3.2. Python version is 3.10.

It doesn't matter where I run fusesoc and even what the command line parameters are (even without), it always gives that error. Now on my home PC with the same OS and packages it works just fine.

I cannot find the string `spi_nor_config_generator` in neither fusesoc nor edalize so I have no idea why it's trying to find it.

**Comment by olofk** [comment]
Yes, if we can find where that `spi_nor_config_generator` is coming from I hope we can get another clue. Clearly something is weird here. @soronpo can you search your disk for that file? I can't reproduce the issue here so I really need both your help to figure out what's going on

**Comment by olofk** [comment]
ok, I did a global search on github and it turns out there's a `spi_nor_config_generator`in the litespi Litex package. The interesting thing is that this module lives in a subpackage called `tools`I wonder Edalize is picking up that for some strange reason

**Comment by olofk** [comment]
Yes. Installing this triggers that bug. God, I hate Python sometimes

**Comment by olofk** [comment]
I just released an Edalize 0.3.3 that I hope will fix this problem. Happy for any feedback

**Comment by olofk** [comment]
FYI, it might be that we're hitting this Python bug https://bugs.python.org/issue14787 that turns 10 years old in less than a month :)

**Comment by soronpo** [comment]
Yes, it works now! Thank you @olofk

**Comment by GuzTech** [comment]
I'm at home so I cannot test if it works, but I assume it will since @soronpo said it does :)

**Comment by soronpo** [comment]
I explicitly installed edalize, FWIW.

**Comment by GuzTech** [comment]
I can confirm too that this problem has been solved. Thank you!
