### ISSUE TITLE
Support Project X-Ray - Xilinx Series 7 Bitstream 

### ISSUE THREAD

**Issue by somhi** [olofk/fusesoc#551]
Need support for Project X-Ray for my kintex 7 xc7k325t
for implementing a blinky like done here https://github.com/kintex-chatter/xc7k325t-blinky-nextpnr

**Comment by mithro** [comment]
See alo https://github.com/olofk/edalize/issues/302

**Comment by mithro** [comment]
FPGA Tool Perf in SymbiFlow uses EDAlize with various Series 7 flows;
 * https://github.com/SymbiFlow/fpga-tool-perf
 * https://chipsalliance.github.io/fpga-tool-perf/

**Comment by somhi** [comment]
Ok perfect. I'll let you know when I try it. 

Thanks.

**Comment by carlosedp** [comment]
I added some support to Edalize on https://github.com/olofk/edalize/pull/308
It's open for comments and might need some refactor in case we homogenize the backends in the futura (under F4PGA or something).
