### ISSUE TITLE
[Bug, simple fix] Yosys, arch=xilinx fails because of syntax error in write_blif command

### ISSUE THREAD

**Issue by armleo** [olofk/fusesoc#569]
Devs, I want to say thank you. Your tool is amazing, it's exactly what I desperately needed for a long time!

Running yosys with following config:
```
  # The "synth" target synthesizes the design. (It could have any name.)
  synth:
    <<: *default
    description: Synthesize using yosys
    default_tool: yosys
    tools:
        yosys:
          arch: xilinx
          
```

I get following error:
```
ERROR: Command syntax error: Unknown option or option in arguments.
> write_blif -pvector bra armleo_armleo_cores_armleo_burstmem_1.0.0.blif
>            ^
make: *** [Makefile:6: armleo_armleo_cores_armleo_burstmem_1.0.0.blif] Error 1
ERROR: Failed to build armleo:armleo_cores:armleo_burstmem:1.0.0 : '['make']' exited with an error: 2
```

According to yosys docs write_blif does not have -pvector. write_edif does.

If the output_format is set to edif, everything works as expected.

**Comment by olofk** [comment]
Thanks for reporting. I think https://github.com/olofk/edalize/pull/332 should have fixed this now. Please reopen otherwise
