### ISSUE TITLE
Installation fails in Python 3.6 environments

### ISSUE THREAD

**Issue by GCHQDeveloper963** [olofk/fusesoc#577]
When pip installing Fusesoc into a Python 3.6 environment installation fails with error:
```python
...
      File "/tmp/pip-ojubvo4_-build/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
```

This is currently visible in the Fusesoc CI ([example](https://github.com/olofk/fusesoc/runs/7243558884?check_suite_focus=true)).

This issue is occurring because the latest major version of `setuptools_scm` drops support for Python 3.6 and uses annotations within it's `setup.py` file, so the Python version check is never reached.

I think there are a few possible approaches to resolving this.

1. Increase the minimum Python version that Fusesoc requires to 3.7.
    - Would mean that Fusesoc could not be installed into the default environment for some operating systems, primarily RHEL 7 and 8 based systems (e.g. AlmaLinux 8; CentOS 7; CentOS Stream 8; Rocky Linux 8; openSUSE Leap). It would also affect Ubuntu 18.04 LTS. However, generally a newer version will be available in some form such as from CentOS SCLo RH for CentOS 7, but may not be usable for some users and would require users to take a proactive step to use a newer version.
2. Limit the maximum version of `setuptools_scm` to `<7`.
    - Would mean that any one running a newer version of Python will also be limited to an older version of `setuptools_scm`. This seems like a less than ideal position to be in and would mean missing out on new features or fixes.
3. `setuptools_scm` could remove the use of Python 3.7+ code from their `setup.py`.
    - Seems unlikely to happen, they deliberately dropped support for older versions so supporting older versions in their `setup.py` just to have a different (but more descriptive) error message on installation seems like a backwards step.

**Comment by olofk** [comment]
Looks like @joennlae is fixing this as part of #579
