### ISSUE TITLE
Generating a filelist

### ISSUE THREAD

**Issue by skilambi** [olofk/fusesoc#584]
Hi all. I am very new to fusesoc. I was wondering if there is a way to generate a filelist for all the registered cores. Maybe this is a very obvious command. 

Sai.

**Comment by shareefj** [comment]
This was discussed in https://github.com/olofk/edalize/issues/25 but it has gone stale.  We're currently using the Filelist backend implemented here: https://github.com/idex-biometrics/edalize/blob/write_filelist/edalize/filelist.py

**Comment by skilambi** [comment]
Thanks for such a quick response. How do I use this python code? Do you
have an example?

Regards,
Sai.

**Comment by shareefj** [comment]
You'll need to copy/fork that repo and pip install it instead of the official Edalize.  I'd suggest having a read of how Fusesoc integrates with Edalize and looking at some of the flows in more detail if you are new to it all.

**Comment by skilambi** [comment]
Thanks alot for the quick response Shareef :). Will do.

Sai.

**Comment by shareefj** [comment]
@skilambi The Edalize branch was merged to main by Olof so feel free to check it out.  I've been working on a separate branch so may not have merged all the fixes so I'll try to find time to check that.  But if you have any requests or issues then open an Edalize ticket and mention me.

**Comment by olofk** [comment]
Yes. I think we can close this and open an Edalize ticket if needed
