### ISSUE TITLE
How to fix Parse Error

### ISSUE THREAD

**Issue by abdullahyildiz** [olofk/fusesoc#590]
We get some warnings related to parsing of .core files in [CORE-V MCU](https://github.com/openhwgroup/core-v-mcu) project:

```
WARNING: Parse error. Ignoring file ./core-v-mcu-emul.core: Unknown item 'description in section Target'
WARNING: Parse error. Ignoring file ./core-v-mcu.core: Unknown item 'description in section Target'
WARNING: Parse error. Ignoring file ./rtl/core-v-mcu/core-v-mcu.core: Unknown item 'description in section Target'
```

We work on CentOS 7 and maybe there is something missing with FuseSoC setup as I do not have such problem on Ubuntu 18.04.5 LTS.

**Comment by abdullahyildiz** [comment]
It is 1.9.2.

**Comment by imphil** [comment]
Please update to the latest version, it looks like 1.9.2 isn't sufficient for the core files you're using.

**Comment by abdullahyildiz** [comment]
Upgrading to version 1.12.0 solved the issue.
