### ISSUE TITLE
Core files are in CAPI1 format, which is not supported Fusesoc 2.0. Migrate CAPI2 format

### ISSUE THREAD

**Issue by Gayatri11-oa** [olofk/fusesoc#604]
Please suggest me how can i solve this Migration Issue.
While "fusesoc init" i am getting this following issues
"ERROR: Core file /home/oa/.local/share/fusesoc/orpsoc-cores/systems/nyuzi_de2_115/nyuzi_de2_115.core is in CAPI1 format, which is not supported any more since FuseSoC 2.0. The core file is ignored. Please migrate your cores to the CAPI2 file format, or use FuseSoC 1.x as stop-gap."

**Comment by imphil** [comment]
@Gayatri11-oa The error message pretty much says it all. 

You can find a migration guide from CAPI1 to CAPI2 at https://fusesoc.readthedocs.io/en/stable/ref/migrations.html#migrating-from-capi1-to-capi2.
