### ISSUE TITLE
Some remotes do not support shallow clones

### ISSUE THREAD

**Issue by GCHQDeveloper137** [olofk/fusesoc#606]
I've recently upgraded to v2.0, and most things are working a charm. One thing has stopped me in my tracks, though, and that's that one of our remote git repos does not support shallow clones. Fusesoc 2 seems to attempt a shallow clone regardless for git, which means any cores that point to remote repositories with the git provider that do not support shallow cloning fail.

The idea of the shallow clone is definitely a good one, particularly for larger repos. I'll submit a simple patch that is working for me that tries to do a shallow clone, but if that fails falls back to trying without.

**Comment by olofk** [comment]
This should be fixed now with #607
