### ISSUE TITLE
why there is 'Could not find generator'?

### ISSUE THREAD

**Issue by chenbo-again** [olofk/fusesoc#654]
when I type fusesoc gen list, I found all I need, but when I just use this generator, it fails.

```
spinalfusesoc ) fusesoc gen list

Available generators:

Core                                Generator
=============================================
::MyTopLevel_generators:0         : MyTopLevel_generator : Build spinalhdl
chenbosoft:utils:generators:0.0.0 : spinalhdl : Build spinalhdl
spinalfusesoc ) fusesoc run --target=lint MyTopLevel_useit
INFO: Preparing ::MyTopLevel_useit:0
ERROR: Setup failed : Could not find generator 'MyTopLevel_generator' requested by ::MyTopLevel_useit:0
```

when I debug Edalizer.cores, I can not found any cores except ::MyTopLevel_useit:0, (seems it do because only this core is in current directory)

**Comment by olofk** [comment]
Have you added the core that contains the generator in the dependency list of the core that uses the generator? That is something I forget myself sometimes :)
