### ISSUE TITLE
Regression: v2.2.1 Doesn't copy files to build directory on Windows

### ISSUE THREAD

**Issue by creiter64** [olofk/fusesoc#655]
With v2.2.1 I can't run my simulations anymore, because fusesoc doesn't copy the source files to the build directory.

It works fine if I downgrade fusesoc to v2.0.

Could be related to: https://github.com/olofk/fusesoc/issues/628

**Comment by olofk** [comment]
Hopefully this and #628 is fixed now with FuseSoC 2.3 Please let me know if it works

**Comment by creiter64** [comment]
Thank you for the new release, I can confirm this is fixed with v2.3
