### ISSUE TITLE
Reseting cache

### ISSUE THREAD

**Issue by gsteiert** [olofk/fusesoc#688]
Is there a way to reset the cache for the python scripts used in generators?
I have a project that thinks it already copied files to /tmp/kdecache-user but they are not there and the build fails.
Where does it store the files it thinks it cached and how do I clear that?
It would be nice to have a reset/clean function.

**Comment by olofk** [comment]
There is `fusesoc gen clean` which should clean out the generator cache, but I'm also curious how this happened in the first place.

**Comment by gsteiert** [comment]
Removed the cache directory and it resolved the issue
