### ISSUE TITLE
Typo in the XDC file for PYNQ-Z2 board

### ISSUE THREAD

**Issue by lharnaldi** [olofk/fusesoc#708]
In the repository it is:
create_clock -add -name sys_clk_pin -period 8 -waveforem {0 4} [get_nets clk];
but must be 
create_clock -add -name sys_clk_pin -period 8 -waveform {0 4} [get_nets clk];

**Comment by olofk** [comment]
Are you sure you are in the right repository?

**Comment by lharnaldi** [comment]
Sorry, You are right. It is related to the led to believe repository in the blinky project. I was testing the fusesoc repo with the blinky project. Should I open an issue in the led to believe repo? Thanks.

**Comment by olofk** [comment]
Yes. Open an issue there instead. Closing this.
